### ISSUE TITLE
Unkown cause of segmentation fault for certain input streams

### ISSUE THREAD

**Issue by Elias-G** [Hjortsberg/fwarm_viewer#8]
When using laptop webcam as camera feed and usbcam as lidar feed causes segmentation fault when running the viewer however it everything works fine when with webcam as lidar and usbcam as camera feed.

**Comment by Hjortsberg** [comment]
Solved by: 9d1b31a552fbdc930a4b0083a9218194119c3248.
Resizes the usbcam videostream.
